import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Shield, Brain, FileText, Sparkles, Upload, ArrowRight,
  BarChart3, Scale, AlertTriangle, Zap
} from "lucide-react";
import { useEffect, useState } from "react";

function AnimatedCounter({ target, label }: { target: string; label: string }) {
  return (
    <div className="text-center">
      <div className="text-2xl font-bold gradient-text">{target}</div>
      <div className="text-xs text-muted-foreground mt-1">{label}</div>
    </div>
  );
}

const features = [
  { icon: Brain, title: "AI Clause Classification", desc: "LegalBERT identifies 11+ clause types with high confidence scoring." },
  { icon: Shield, title: "10-Signal Risk Engine", desc: "Detects unlimited liability, forced arbitration, one-sided termination & more." },
  { icon: Sparkles, title: "Gemini AI Explanations", desc: "Plain-English risk explanations generated by Google Gemini for every high-risk clause." },
  { icon: FileText, title: "Suggested Rewrites", desc: "AI-generated alternative clause language that reduces risk exposure." },
];

const steps = [
  { num: "01", title: "Upload Contract", desc: "Drag and drop PDF, DOCX, or TXT files.", icon: Upload },
  { num: "02", title: "AI Analyzes Every Clause", desc: "LegalBERT + 10-signal engine scores each clause.", icon: BarChart3 },
  { num: "03", title: "Get Risk Report", desc: "View detailed risk breakdown with explanations.", icon: AlertTriangle },
];

const riskCategories = [
  { label: "Financial Exposure", color: "bg-risk-high/15 text-risk-high border-risk-high/30" },
  { label: "Power Imbalance", color: "bg-risk-medium/15 text-risk-medium border-risk-medium/30" },
  { label: "Dispute Risk", color: "bg-risk-low/15 text-risk-low border-risk-low/30" },
  { label: "General", color: "bg-risk-info/15 text-risk-info border-risk-info/30" },
];

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({ opacity: 1, y: 0, transition: { delay: i * 0.1, duration: 0.5 } }),
};

export default function LandingPage() {
  return (
    <Layout>
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent" />
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-primary/10 rounded-full blur-[120px]" />
        <div className="container relative py-24 md:py-32 text-center">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border bg-card/50 text-xs text-muted-foreground mb-6">
              <Zap className="h-3 w-3 text-primary" /> Powered by LegalBERT + Gemini AI
            </div>
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-extrabold tracking-tight max-w-4xl mx-auto leading-[1.1]">
              AI-Powered Contract{" "}
              <span className="gradient-text">Risk Intelligence</span>
            </h1>
            <p className="mt-6 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
              Upload any legal contract. Get instant clause-by-clause risk scoring powered by LegalBERT + Gemini AI.
            </p>
            <div className="mt-8 flex items-center justify-center gap-4">
              <Button asChild variant="hero" size="lg" className="text-base px-8 h-12">
                <Link to="/upload">
                  Analyze a Contract <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="glass" size="lg" className="h-12">
                <Link to="/about">Learn More</Link>
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="container py-20">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeUp}
              className="glass-card-hover p-6 group"
            >
              <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <f.icon className="h-5 w-5 text-primary" />
              </div>
              <h3 className="font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="container py-20">
        <h2 className="text-3xl font-bold text-center mb-12">
          How It <span className="gradient-text">Works</span>
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
          <div className="hidden md:block absolute top-12 left-[20%] right-[20%] h-px bg-gradient-to-r from-transparent via-border to-transparent" />
          {steps.map((s, i) => (
            <motion.div
              key={s.num}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeUp}
              className="text-center relative"
            >
              <div className="mx-auto h-14 w-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-4">
                <s.icon className="h-6 w-6 text-primary" />
              </div>
              <span className="text-xs font-mono text-primary">{s.num}</span>
              <h3 className="font-semibold mt-1 mb-2">{s.title}</h3>
              <p className="text-sm text-muted-foreground">{s.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Risk Categories */}
      <section className="container py-16">
        <h2 className="text-2xl font-bold text-center mb-8">Risk Categories Detected</h2>
        <div className="flex flex-wrap justify-center gap-3">
          {riskCategories.map((c) => (
            <span key={c.label} className={`px-4 py-2 rounded-full text-sm font-medium border ${c.color}`}>
              {c.label}
            </span>
          ))}
        </div>
      </section>

      {/* Stats */}
      <section className="container py-16">
        <div className="glass-card p-8 flex flex-wrap justify-around gap-8">
          <AnimatedCounter target="10+" label="Risk Signals Detected" />
          <AnimatedCounter target="11+" label="Clause Types Classified" />
          <AnimatedCounter target="LegalBERT" label="Powered Classification" />
          <AnimatedCounter target="Gemini AI" label="Explanations Engine" />
        </div>
      </section>
    </Layout>
  );
}
